atol: 0.02
warmup: 20
repeat: 100

# prefill_paged:
#   batch_size: [1, 2, 8, 16, 32]
#   seq_len: [4096]
#   num_heads: [4, 8]
#   num_kv_heads: [1]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["flashinfer"]

# prefill_ragged:
#   batch_size: [1, 2, 8, 16, 32]
#   seq_len: [4096]
#   num_heads: [4, 8]
#   num_kv_heads: [1]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["flashinfer"]

# decode:
#   batch_size: [4]
#   seq_len: [512, 1024, 2048, 4096, 5120, 6144, 7168, 8192, 9216, 10240]
#   num_heads: [4, 8]
#   num_kv_heads: [1]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["hpc", "sgl-flash_attn", "flashinfer"]

# decode:
#   batch_size: [1, 2, 3, 4, 5, 6, 7, 8, 16, 32]
#   seq_len: [2048]
#   num_heads: [4]
#   num_kv_heads: [1]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["hpc"]

# decode:
#   batch_size: [1, 2, 3, 4, 5, 6, 7, 8, 16, 32]
#   seq_len: [2048]
#   num_heads: [8]
#   num_kv_heads: [1]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["hpc"]

# decode:
#   batch_size: [1, 2, 3, 4, 5, 6, 7, 8, 16, 32]
#   seq_len: [2047]
#   num_heads: [16]
#   num_kv_heads: [2]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["hpc"]

# decode:
#   batch_size: [1, 2, 3, 4, 5, 6, 7, 8, 16, 32]
#   seq_len: [2048]
#   num_heads: [32]
#   num_kv_heads: [8]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["flashinfer"]

decode:
  batch_size: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
  seq_len: [512, 1024, 2048, 4096, 8192]
  num_heads: [40]
  num_kv_heads: [8]
  head_dim: [128]
  page_size: [64]
  operators: ["hpc", "hpc-splitk", "sgl-flash_attn"]

# decode:
#   batch_size: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
#   seq_len: [5120]
#   num_heads: [8]
#   num_kv_heads: [1]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["hpc", "sgl-flash_attn", "flashinfer"]

# prefill_paged:
#   batch_size: [1, 2, 3, 4, 5, 6, 7, 8]
#   seq_len: [2048, 5120]
#   num_heads: [16]
#   num_kv_heads: [2]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["hpc1"]

# prefill_paged:
#   batch_size: [4]
#   seq_len: [8848]
#   num_heads: [16]
#   num_kv_heads: [16]
#   head_dim: [128]
#   page_size: [64]
#   operators: ["flash_attn_v4"]
